### ISSUE TITLE
Please support building with system libsodium

### ISSUE THREAD

**Issue by joshtriplett** [dswd/vpncloud.rs#15]
vpncloud builds its own copy of libsodium, and doesn't seem to support using a system version instead.  Please consider adding support to build against the system version of libsodium, finding it using pkg-config, and only building a copy if not found.

It looks like `build.rs` pulls in `pkg_config`, but doesn't actually use it.  You might also find [metadeps](https://docs.rs/metadeps/) useful, which lets you declare your pkg-config dependencies in `Cargo.toml`.

**Comment by dswd** [comment]
I added a feature called `system-libsodium` which links to the system library instead of building libsodium statically. However, please be aware that libsodium had some performance improvements in its latest releases that you will miss out on if you are linking to an older system lib.
