### ISSUE TITLE
Does vpncloud.rs support compresstion？

### ISSUE THREAD

**Issue by bhzhu203** [dswd/vpncloud.rs#20]
Does vpncloud.rs support compresstion？like snappy？Thanks

**Comment by dswd** [comment]
No, vpncloud does not support compression. I don't think compression would be useful for several reasons:
* Most of the big content like media files and downloads are already compressed and can't be compressed anymore
* A lot of payload protocols already compress (e.g. HTTP) their contents or encrypt them (e.g. HTTPs) so compression can not work
* Even the fastest compression would add a huge overhead for packet processing that would massively degrade performance

Sorry for the late reply.

**Comment by bhzhu203** [comment]
In some situations,we need  the compressing  plaintext content feature,like transfering mysql(slave) plaintext data.It can reduce transfering time and improve download speed.

1.openvpn already supports lzo compression .

2.kcptun use KCP proto/ snappy  compression  /  Reed–Solomon technology to speed up the download speed from 68Kbps to 31Mbps !  https://github.com/xtaci/kcptun

3. Btrfs filesystem have lzo/zstd  compression feature ,and also has 2 modes : smart mode and force mode.
In smart mode :
"There is a simple decision logic: if the first portion of data being compressed is not smaller than the original, the compression of the file is disabled -- unless the filesystem is mounted with -o compress-force."
By the way,we can use the compress  feature which is in Btrfs to reduce the disk IO over 
the CPU usage.

**Comment by corporatepiyush** [comment]
If you don't wish provide it as default ... at least give an option for pluggable compression(lib, zstd etc.) so that user can choose whenever they want.
