### ISSUE TITLE
Compile on Centos 7

### ISSUE THREAD

**Issue by Kali-lightsaber** [dswd/vpncloud.rs#21]

**Comment by sammosna** [comment]
I have the same problem wit Raspbian
---
running 25 tests
test tests::address_eq ... ok
test tests::address_decode_encode ... ok
test tests::address_parse_fmt ... ok
test tests::address_range_decode_encode ... ok
test tests::decode_frame_with_vlan ... ok
test tests::decode_frame_without_vlan ... ok
test tests::config_merge ... ok
test tests::decode_invalid_packet ... ok
test tests::decode_ipv6_packet ... ok
test tests::decode_invalid_frame ... ok
test tests::encrypt_decrypt_aes256 ... ok
test tests::config_file ... ok
test tests::decode_ipv4_packet ... ok
test tests::routing_table_ipv4 ... ok
test tests::message_fmt ... ok
test tests::udpmessage_close ... ok
test tests::routing_table_ipv6 ... FAILED
test tests::udpmessage_init ... ok
test tests::udpmessage_invalid ... ok
test tests::udpmessage_encrypted ... ok
test tests::udpmessage_packet ... ok
test tests::udpmessage_peers ... ok
test tests::udpmessage_invalid_crypto ... ok
test tests::encrypt_decrypt_chacha20poly1305 ... ok
test tests::switch ... ok

failures:

---- tests::routing_table_ipv6 stdout ----
	thread 'tests::routing_table_ipv6' panicked at 'called `Result::unwrap()` on an `Err` value: Parse("Failed to parse address")', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
