### ISSUE TITLE
tests::routing_table_ipv6 panicked

### ISSUE THREAD

**Issue by der-andrew** [dswd/vpncloud.rs#23]
Repeat this https://github.com/dswd/vpncloud.rs/issues/21

On system:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

=====================================

Full stacktrace:
   0:     0x55b1485d933f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h50ace92fd59f6d6f
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55b1485cad96 - std::sys_common::backtrace::print::h1aeedd3135565ede
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x55b1485c7cdd - std::panicking::default_hook::{{closure}}::h439428ff9d34054c
                               at libstd/panicking.rs:211
   3:     0x55b1485c79de - std::panicking::default_hook::h17969c00800f0f09
                               at libstd/panicking.rs:221
   4:     0x55b1485c8387 - std::panicking::rust_panic_with_hook::ha972a0b09b26e11a
                               at libstd/panicking.rs:475
   5:     0x55b1485c7f49 - std::panicking::continue_panic_fmt::h8c35cf0942d76c8d
                               at libstd/panicking.rs:390
   6:     0x55b1485c7e45 - rust_begin_unwind
                               at libstd/panicking.rs:325
   7:     0x55b1485f1e4b - core::panicking::panic_fmt::h3a3d612c054b28ad
                               at libcore/panicking.rs:77
   8:     0x55b1484651b5 - core::result::unwrap_failed::hf622439d7fde6208
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libcore/macros.rs:26
   9:     0x55b148461fff - <core::result::Result<T, E>>::unwrap::h0597ab019a24bd5d
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libcore/result.rs:782
  10:     0x55b1484d5fb8 - vpncloud::tests::routing_table_ipv6::h92365107a4bd9117
                               at src/tests.rs:321
  11:     0x55b1484b7099 - vpncloud::__test::TESTS::{{closure}}::h0d0b14a7876e7f5a
                               at src/tests.rs:293
  12:     0x55b148474fbd - core::ops::function::FnOnce::call_once::h952c76ab5268cb62
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libcore/ops/function.rs:223
  13:     0x55b148510dde - <F as alloc::boxed::FnBox<A>>::call_box::h01e6284b4a2f638a
                               at libtest/lib.rs:1451
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libcore/ops/function.rs:223
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/liballoc/boxed.rs:642
  14:     0x55b1485e4be9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  15:     0x55b148532a31 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb3ed30d07fd3df77
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/panicking.rs:289
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/panic.rs:392
                               at libtest/lib.rs:1406
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/sys_common/backtrace.rs:136
  16:     0x55b1485334c4 - std::panicking::try::do_call::hcf5e155b62c02e29
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/thread/mod.rs:409
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/panic.rs:313
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/panicking.rs:310
  17:     0x55b1485e4be9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  18:     0x55b148528486 - <F as alloc::boxed::FnBox<A>>::call_box::haeb2d577a62c69de
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/panicking.rs:289
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/panic.rs:392
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/libstd/thread/mod.rs:408
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/liballoc/boxed.rs:642
  19:     0x55b1485c9b7a - std::sys_common::thread::start_thread::h08d455f825e7860f
                               at /builddir/build/BUILD/rustc-1.29.1-src/src/liballoc/boxed.rs:652
                               at libstd/sys_common/thread.rs:24
  20:     0x55b1485c88e5 - std::sys::unix::thread::Thread::new::thread_start::he9982eba441a6325
                               at libstd/sys/unix/thread.rs:90
  21:     0x7ff436710e24 - start_thread
  22:     0x7ff436224bac - __clone
  23:                0x0 - <unknown>

failures:
    tests::routing_table_ipv6

test result: FAILED. 24 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--bin vpncloud'
make: *** [test] Error 101

**Comment by dswd** [comment]
This should be fixed in latest update. Although the panic should have been a normal test failure, pretty curious...
