### ISSUE TITLE
Destination Host Unreachable after about 300s

### ISSUE THREAD

**Issue by fourbytes** [dswd/vpncloud.rs#4]
I've got 3 nodes running with tap and on the default (switch) mode, and after about 300 seconds (default value for DST_TIMEOUT). One of the nodes seem to stop communicating with some of it's peers (not all). There doesn't seem to be anything obvious in the logs either.

**Comment by dswd** [comment]
Hi, that is interesting. To clarify: Do you have continuous payload traffic during those 300 seconds or is there 300 seconds of complete silence?
To help debug your problem please:
1) Increase the log level using `-v`
2) Run the test again using different values for `dst_timeout` (e.g. 150 and 600)
3) Keep a look on the output of `arp -n` when it is working and when it is not

In theory the `dst_timeout` should not be able to cause this behavior. If you run into this timeout it should cause a broadcast to all peers and not a silent drop.

**Comment by fourbytes** [comment]
I was pinging it so it was receiving continuous traffic, however after messing around with the peer lists and adding another peer, the issue seems to have disappeared, looks like it was probably a fluke but I'll keep an eye on it and reopen this if I can find a way to reproduce it.

Thanks

**Comment by fourbytes** [comment]
Alright, possibly related, but after having them all running for about 12 hours, 1 of the nodes (host_c) is now disconnected from all the others but there is nothing obvious in the log. 10.42.0.0/24 is the vpn subnet.

```
log on the disconnected host (host_c)
INFO - Forgot address 3a:35:39:66:32:37
INFO - New peer: host_b:3210
INFO - New peer: host_a:3210
INFO - Forgot address 70:73:cb:db:ee:93
INFO - Forgot address e2:be:8d:82:6b:8f
INFO - Forgot address a6:da:6d:a8:81:45
INFO - Forgot address 14:cc:20:0c:5c:ef
INFO - Forgot address 54:a0:50:56:db:99
INFO - Forgot address 32:61:63:37:33:62
INFO - Forgot address 5c:f9:38:89:c7:48
```

```
1 root@host_c /root/ # ping 10.42.0.12       :(
PING 10.42.0.12 (10.42.0.12) 56(84) bytes of data.
From 10.42.0.22 icmp_seq=1 Destination Host Unreachable
From 10.42.0.22 icmp_seq=2 Destination Host Unreachable
From 10.42.0.22 icmp_seq=3 Destination Host Unreachable
From 10.42.0.22 icmp_seq=4 Destination Host Unreachable
```

```
root@host_c /root/ # arp -n
Address                  HWtype  HWaddress           Flags Mask            Iface
10.42.0.120                      (incomplete)                              vpncloud0
10.42.0.12                       (incomplete)                              vpncloud0
10.42.0.1                        (incomplete)                              vpncloud0
```

Trying to ping this server from the other nodes also shows (incomplete) for the disconnected host's IP when running arp -n. Running top also confirms that vpncloud is still running.

After restarting vpncloud the node is connected again. I'll increase the log level to debug and see if I get anything else if it happens again.

I'm assuming this is a separate issue but I also get the following repeated in the logs on some of the nodes.
```
WARN - Destination for 5c:f9:38:89:c7:48 not found in peers: host_a:3210
INFO - Learned address 5c:f9:38:89:c7:48 => host_a:3210
WARN - Destination for 5c:f9:38:89:c7:48 not found in peers: host_a:3210
INFO - Learned address 5c:f9:38:89:c7:48 => host_a:3210
WARN - Destination for 5c:f9:38:89:c7:48 not found in peers: host_a:3210
INFO - Learned address 5c:f9:38:89:c7:48 => host_a:3210
(this spams the log quite a bit)
```

**Comment by dswd** [comment]
Ok, I think you found an actual problem. When control messages get lost, peers can disagree about whether they are connected and the reconnect then does not work. I changed to code to fix this. Can you try the latest code?

**Comment by fourbytes** [comment]
Alright, looking good since ab7c0333, none of the nodes seem to have unexpectedly dropped since I deployed that commit about 3 days ago :)

Also just to let you know I've whipped up a quick AUR package for arch linux (https://aur.archlinux.org/packages/vpncloud/).

**Comment by dswd** [comment]
Oh that is great! I think I will then release version 0.7 containing this fix soon.

Also thanks for packaging vpncloud. Do you plan to package future versions too? Then I would add a linnk to your repository to the front page.

I had a quick look on your package (not that I am familiar with AUR packages). I did not see any commands related to building and installing the manpage.

**Comment by fourbytes** [comment]
Ah, forgot about the man page, will update the package to build that tonight, and yep I plan on packaging future versions as well, one of the cool things about the AUR is that you only provide the build script and then the user runs that on their machine, and if I ever stopped maintaining it, another member of the AUR could take over and continue updating the same package.
