### ISSUE TITLE
Some suggestion of packet header.

### ISSUE THREAD

**Issue by yuko1225** [dswd/vpncloud.rs#5]
Hello,

I think the 8 byte header still contain too much information(especially the “'vpn' magic number").In some environment you will need a protocol which has no signature otherwise it could be blocked by Deep packet inspection.

It will be better if you do some fast obfuscate to the header or at least make it as an option.

Thanks.

**Comment by dswd** [comment]
Oh yes, you are right. I did not optimize the protocol for stealthiness or deniability but I can see this use case.
A configurable "vpn" magic number (or even a random one that will be ignored completely) would be good in this case. This feature could even replace the network-id as it has the same behavior.
As this is a breaking change, it is the right time to do this before 1.0.

**Comment by dswd** [comment]
I implemented the change. Now you can use the `--magic` argument to set the magic number in the header, quoting the manpage:

`--magic <id>`:

    Override the 4-byte magic header of each packet. This header identifies the
    network and helps to distinguish it from other networks and other
    applications. The id can either be a 4 byte / 8 character hexadecimal
    string or an arbitrary string prefixed with "hash:" which will then be
    hashed into 4 bytes.
