### ISSUE TITLE
Consider proper systemd support

### ISSUE THREAD

**Issue by fourbytes** [dswd/vpncloud.rs#8]
At the moment using `vpncloud-control` is a bit awkward, would be much better to provide systemd integration since most distros nowadays use it, also means that we can have systemd keep track of the process directly.

Slightly related to this would be supporting proper config files (possibly using TOML) instead of just command line options (but still keep support for cli options).

I'm happy to push a basic systemd config if you want to merge it in.

**Comment by dswd** [comment]
A TOML config file is a great idea, I will take care of that.
Systemd is a problem for me, I am still working with Ubuntu 14.04. If you could provide a working config that would be great.

**Comment by fourbytes** [comment]
Awesome, will do systemd configs properly when you've done toml configs. 👍

**Comment by dswd** [comment]
Done. I went with YAML as its syntax is easier for non-developers.

**Comment by fourbytes** [comment]
Awesome! I'll try get round to systemd configs today.

**Comment by dswd** [comment]
The latest commit features a service file that adds systemd support.
